---
- name: "Add an /etc/hosts entry for your IP address"
  ansible.builtin.template:
    src: "./template/hosts"
    dest: "/etc/hosts"
    backup: "yes"
        
- name: "Add Proxmox VE repository key for Trixie"
  get_url:
    url: "https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg"
    dest: "/usr/share/keyrings/proxmox-archive-keyring.gpg"
    mode: '0644'
    owner: root
    group: root
    checksum: "sha256:136673be77aba35dcce385b28737689ad64fd785a797e57897589aed08db6e45"
    
- name: "Create Proxmox repository configuration (deb822 format)"
  copy:
    dest: "/etc/apt/sources.list.d/pve-install-repo.sources"
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/pve
      Suites: trixie
      Components: pve-no-subscription
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
    mode: '0644'
    owner: root
    group: root

- name: "Update your repository and system by running:"
  apt:
    update_cache: "yes"
    upgrade: "dist"

- name: "/etc/network/interfaces edit"
  ansible.builtin.template:
    backup: "yes"
    src: "./template/interfaces"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: 0644

- name: "Install other packages"
  apt:
    name: "{{ item }}"
    update_cache: "yes"
    state: "latest"
    install_recommends: "yes"
  with_items:
  - bridge-utils

- name: "Install the Proxmox VE Kernel"
  apt:
    name: proxmox-default-kernel
    update_cache: "yes"
    state: "latest"
    install_recommends: "yes"
  register: kernel_update

- name: "Reboot"
  shell: nohup bash -c "sleep 2s && reboot" &
  when: kernel_update.changed
  async: 0
  poll: 0
  ignore_errors: true
  register: reboot      
      
- name: Wait for the host to finish rebooting
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=120 connect_timeout=1200
  become: false
  delegate_to: localhost
  when: reboot.changed

- name: "Install other packages"
  apt:
    name: "{{ item }}"
    update_cache: "yes"
    state: "latest"
    install_recommends: "yes"
  with_items:
  - proxmox-ve
  - postfix
  - open-iscsi
  - chrony

- name: "off enterprise repository"
  lineinfile:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    regex: "deb https://.*"
    line: "#deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
    state: "present"

- name: "Remove the os-prober Package"
  apt:
    name: "os-prober"
    state: "absent"

- name: search for standard kernels
  shell: "$( which dpkg ) --get-selections linux-image* | $( which grep ) -i install | $(which awk) '{print $1}'"
  args:
    executable: /bin/bash
  register: standart_kernels_installed

- name: remove standart kernels
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ standart_kernels_installed.stdout_lines|default([]) }}"

- name: "Update GRUB"
  command: "update-grub"

- name: "rebooting the server"
  shell: nohup bash -c "sleep 2s && reboot" &
  async: 0
  poll: 0
  ignore_errors: yes
  register: reboot
  tags: reboot
...